export interface ProgramExample {
  id: string;
  name: string;
  source: string;
}

export const PROGRAM_EXAMPLES: readonly ProgramExample[] = [
  {
    id: "zbir",
    name: "Zbir brojeva 1-5",
    source: [
      "# Zbir brojeva od 1 do 5",
      "LI x1, 0        # zbir",
      "LI x2, 1        # brojac",
      "LI x3, 6        # granica",
      "",
      "petlja:",
      "ADD x1, x1, x2",
      "ADDI x2, x2, 1",
      "BLT x2, x3, petlja",
      "",
      "SW x1, 0(x0)    # rezultat 15 na adresi 0",
    ].join("\n"),
  },
  {
    id: "aritmetika",
    name: "Aritmetika i logika",
    source: [
      "# Aritmeticke, logicke i shift instrukcije",
      "LI x1, 12",
      "LI x2, 5",
      "",
      "ADD x3, x1, x2  # 17",
      "SUB x4, x1, x2  # 7",
      "AND x5, x1, x2  # 4",
      "OR  x6, x1, x2  # 13",
      "XOR x7, x1, x2  # 9",
      "",
      "LI x8, 2",
      "SLL x9, x2, x8  # 20",
      "SRL x10, x1, x8 # 3",
      "MV x11, x3      # kopija rezultata ADD",
      "NOP",
    ].join("\n"),
  },
  {
    id: "memorija",
    name: "Rad sa memorijom",
    source: [
      "# Upis dve vrednosti, citanje i cuvanje zbira",
      "LI x1, 8         # bazna adresa",
      "LI x2, 10",
      "LI x3, 20",
      "",
      "SW x2, 0(x1)    # memorija[8] = 10",
      "SW x3, 4(x1)    # memorija[12] = 20",
      "LW x4, 0(x1)",
      "LW x5, 4(x1)",
      "ADD x6, x4, x5",
      "SW x6, 8(x1)    # memorija[16] = 30",
    ].join("\n"),
  },
  {
    id: "funkcija",
    name: "Funkcija i grananje",
    source: [
      "# Poziv funkcije i provera rezultata",
      "LI x5, 4",
      "JAL x1, dupliraj",
      "",
      "LI x6, 8",
      "BEQ x5, x6, jednako",
      "LI x7, -1       # izvrsava se samo ako rezultat nije 8",
      "J kraj",
      "",
      "jednako:",
      "LI x7, 1",
      "BNE x7, x0, kraj",
      "LI x7, -2       # ova linija se preskace",
      "",
      "kraj:",
      "SW x5, 0(x0)    # rezultat funkcije: 8",
      "SW x7, 4(x0)    # rezultat provere: 1",
      "J gotovo",
      "",
      "dupliraj:",
      "ADD x5, x5, x5",
      "RET",
      "",
      "gotovo:",
    ].join("\n"),
  },
];
